
export const style = {
  'hand_wash': 'button pressed green width_450',
  'self_wash': 'button pressed blue',
  'top_container': 'flex_container justify_space_between flex_direction_column h_w_100',
  'middle_container': 'flex_item_stretch flex_container flex_wrap justify_center flex_direction_column align_items_center',
  'bar_top_5': 'flex_bar padding_top_5p',
  'bar_5': 'flex_bar padding_5p',
  'bar': 'flex_bar',
  'nav_container': 'flex_bar padding_5p flex_container flex_wrap justify_center flex_direction_column',
  'nav_button_green': 'flex_item_row button pressed green width_350',
  'input': 'flex_item_row button white text_center',
  'input_red': 'flex_item_row button white text_center border_red',
  'keyboard_button': 'flex_item_row button pressed green width_100',
  'keyboard_button_cancel': 'flex_item_row button pressed red width_220',
  'nav_button_red': 'flex_item_row button pressed red width_220',
  'col_container': 'flex_item_stretch flex_container flex_nowrap justify_center flex_direction_column',
  'list_container': 'align_items_center flex_container flex_wrap justify_center flex_direction_row',
  'list_container_width_450': 'flex_bar align_items_center flex_container flex_wrap justify_center flex_direction_row width_450 padding_top_5p',
  'nav_button_blue': 'flex_item_row button pressed blue width_350',
  'nav_button_selected': 'flex_item_row button pressed selected width_350',
  'disabled_button_ligth_blue': 'flex_item_row button disabled ligth_blue width_350',
  'disabled_button_red': 'flex_item_row button disabled red width_350',
}
